---
baseURL: https://minecraft.asylum.zone/
languageCode: en-us
title: asylum minecraft

module:
  imports:
    # path: github.com/adityatelange/hugo-PaperMod
    - path: github.com/kdevo/osprey-delight/v5


params:
  author:
    name: raizyr
  description: "asylum Minecraft Server & modpack"

  theme: dedark
