name = "asylum minecraft smp"
author = "raizyr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ff800d0fd3c3845ec8fc9bbc66b8e24685baaffff292c5d148f98fe13dee621"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"
